baseURL = "https://athuull.github.io/"
title = "MyDevLog"
pagination.pagerSize = 5
theme = ["PaperMod"]
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts"]

[minify]
disableXML = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    taxonomies = { category = "categories", tag = "tags" }
    [[languages.en.menu.main]]
      name = "About Me"
      url = "about/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Posts"
      url = "posts/"
      weight = 5

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "Follow my journey"
author = "Athul"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowToc = true
images = ["images/devlog-cover.png"]

  [params.homeInfoParams]
    Title = "Welcome to My DevLog"
    Content = """
  ðŸ‘‹ Hey, I'm Athul! This blog serves as documentation of my journey with tech.
  Follow along as I explore new tools, projects, and trends.
  Feel free to explore and connect!
  """

  [[params.socialIcons]]
    name = "github"
    title = "Check out my GitHub"
    url = "https://github.com/athuull"
  [[params.socialIcons]]
    name = "LinkedIn"
    title = "Connect with me on LinkedIn"
    url = "https://www.linkedin.com/in/athul-v-anil-094808222/"

[markup.goldmark.renderer]
unsafe = true
